# This file is generated automatically by generate_SpeciesName_bind_test.py.
# Do not modify this file, but modify the script instead.
import kimpy

attributes = [
  kimpy.species_name.electron,
  kimpy.species_name.H,
  kimpy.species_name.He,
  kimpy.species_name.Li,
  kimpy.species_name.Be,
  kimpy.species_name.B,
  kimpy.species_name.C,
  kimpy.species_name.N,
  kimpy.species_name.O,
  kimpy.species_name.F,
  kimpy.species_name.Ne,
  kimpy.species_name.Na,
  kimpy.species_name.Mg,
  kimpy.species_name.Al,
  kimpy.species_name.Si,
  kimpy.species_name.P,
  kimpy.species_name.S,
  kimpy.species_name.Cl,
  kimpy.species_name.Ar,
  kimpy.species_name.K,
  kimpy.species_name.Ca,
  kimpy.species_name.Sc,
  kimpy.species_name.Ti,
  kimpy.species_name.V,
  kimpy.species_name.Cr,
  kimpy.species_name.Mn,
  kimpy.species_name.Fe,
  kimpy.species_name.Co,
  kimpy.species_name.Ni,
  kimpy.species_name.Cu,
  kimpy.species_name.Zn,
  kimpy.species_name.Ga,
  kimpy.species_name.Ge,
  kimpy.species_name.As,
  kimpy.species_name.Se,
  kimpy.species_name.Br,
  kimpy.species_name.Kr,
  kimpy.species_name.Rb,
  kimpy.species_name.Sr,
  kimpy.species_name.Y,
  kimpy.species_name.Zr,
  kimpy.species_name.Nb,
  kimpy.species_name.Mo,
  kimpy.species_name.Tc,
  kimpy.species_name.Ru,
  kimpy.species_name.Rh,
  kimpy.species_name.Pd,
  kimpy.species_name.Ag,
  kimpy.species_name.Cd,
  kimpy.species_name.In,
  kimpy.species_name.Sn,
  kimpy.species_name.Sb,
  kimpy.species_name.Te,
  kimpy.species_name.I,
  kimpy.species_name.Xe,
  kimpy.species_name.Cs,
  kimpy.species_name.Ba,
  kimpy.species_name.La,
  kimpy.species_name.Ce,
  kimpy.species_name.Pr,
  kimpy.species_name.Nd,
  kimpy.species_name.Pm,
  kimpy.species_name.Sm,
  kimpy.species_name.Eu,
  kimpy.species_name.Gd,
  kimpy.species_name.Tb,
  kimpy.species_name.Dy,
  kimpy.species_name.Ho,
  kimpy.species_name.Er,
  kimpy.species_name.Tm,
  kimpy.species_name.Yb,
  kimpy.species_name.Lu,
  kimpy.species_name.Hf,
  kimpy.species_name.Ta,
  kimpy.species_name.W,
  kimpy.species_name.Re,
  kimpy.species_name.Os,
  kimpy.species_name.Ir,
  kimpy.species_name.Pt,
  kimpy.species_name.Au,
  kimpy.species_name.Hg,
  kimpy.species_name.Tl,
  kimpy.species_name.Pb,
  kimpy.species_name.Bi,
  kimpy.species_name.Po,
  kimpy.species_name.At,
  kimpy.species_name.Rn,
  kimpy.species_name.Fr,
  kimpy.species_name.Ra,
  kimpy.species_name.Ac,
  kimpy.species_name.Th,
  kimpy.species_name.Pa,
  kimpy.species_name.U,
  kimpy.species_name.Np,
  kimpy.species_name.Pu,
  kimpy.species_name.Am,
  kimpy.species_name.Cm,
  kimpy.species_name.Bk,
  kimpy.species_name.Cf,
  kimpy.species_name.Es,
  kimpy.species_name.Fm,
  kimpy.species_name.Md,
  kimpy.species_name.No,
  kimpy.species_name.Lr,
  kimpy.species_name.Rf,
  kimpy.species_name.Db,
  kimpy.species_name.Sg,
  kimpy.species_name.Bh,
  kimpy.species_name.Hs,
  kimpy.species_name.Mt,
  kimpy.species_name.Ds,
  kimpy.species_name.Rg,
  kimpy.species_name.Cn,
  kimpy.species_name.Nh,
  kimpy.species_name.Fl,
  kimpy.species_name.Mc,
  kimpy.species_name.Lv,
  kimpy.species_name.Ts,
  kimpy.species_name.Og,
  kimpy.species_name.user01,
  kimpy.species_name.user02,
  kimpy.species_name.user03,
  kimpy.species_name.user04,
  kimpy.species_name.user05,
  kimpy.species_name.user06,
  kimpy.species_name.user07,
  kimpy.species_name.user08,
  kimpy.species_name.user09,
  kimpy.species_name.user10,
  kimpy.species_name.user11,
  kimpy.species_name.user12,
  kimpy.species_name.user13,
  kimpy.species_name.user14,
  kimpy.species_name.user15,
  kimpy.species_name.user16,
  kimpy.species_name.user17,
  kimpy.species_name.user18,
  kimpy.species_name.user19,
  kimpy.species_name.user20,
]


str_names = [
  "electron",
  "H",
  "He",
  "Li",
  "Be",
  "B",
  "C",
  "N",
  "O",
  "F",
  "Ne",
  "Na",
  "Mg",
  "Al",
  "Si",
  "P",
  "S",
  "Cl",
  "Ar",
  "K",
  "Ca",
  "Sc",
  "Ti",
  "V",
  "Cr",
  "Mn",
  "Fe",
  "Co",
  "Ni",
  "Cu",
  "Zn",
  "Ga",
  "Ge",
  "As",
  "Se",
  "Br",
  "Kr",
  "Rb",
  "Sr",
  "Y",
  "Zr",
  "Nb",
  "Mo",
  "Tc",
  "Ru",
  "Rh",
  "Pd",
  "Ag",
  "Cd",
  "In",
  "Sn",
  "Sb",
  "Te",
  "I",
  "Xe",
  "Cs",
  "Ba",
  "La",
  "Ce",
  "Pr",
  "Nd",
  "Pm",
  "Sm",
  "Eu",
  "Gd",
  "Tb",
  "Dy",
  "Ho",
  "Er",
  "Tm",
  "Yb",
  "Lu",
  "Hf",
  "Ta",
  "W",
  "Re",
  "Os",
  "Ir",
  "Pt",
  "Au",
  "Hg",
  "Tl",
  "Pb",
  "Bi",
  "Po",
  "At",
  "Rn",
  "Fr",
  "Ra",
  "Ac",
  "Th",
  "Pa",
  "U",
  "Np",
  "Pu",
  "Am",
  "Cm",
  "Bk",
  "Cf",
  "Es",
  "Fm",
  "Md",
  "No",
  "Lr",
  "Rf",
  "Db",
  "Sg",
  "Bh",
  "Hs",
  "Mt",
  "Ds",
  "Rg",
  "Cn",
  "Nh",
  "Fl",
  "Mc",
  "Lv",
  "Ts",
  "Og",
  "user01",
  "user02",
  "user03",
  "user04",
  "user05",
  "user06",
  "user07",
  "user08",
  "user09",
  "user10",
  "user11",
  "user12",
  "user13",
  "user14",
  "user15",
  "user16",
  "user17",
  "user18",
  "user19",
  "user20",
]



def test_main():
    """Main test function."""
    N = kimpy.species_name.get_number_of_species_names()

    assert N == 139

    all_instances = []
    for i in range(N):
        inst = kimpy.species_name.get_species_name(i)

        all_instances.append(inst)

        assert inst == attributes[i]
        assert str(inst) == str_names[i]

    # test operator overloading
    for i in range(N):
        assert all_instances[i] == all_instances[i]

        for j in range(i + 1, N):
            assert all_instances[i] != all_instances[j]

    # test known
    for inst in all_instances:
        assert inst.known() == True

    # test out of bound
    capture_out_of_bound_error = False

    try:
        inst = kimpy.species_name.get_species_name(N)
    except RuntimeError:
        capture_out_of_bound_error = True

    assert capture_out_of_bound_error


if __name__ == "__main__":
    test_main()
