name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v1.8.1
        with:
          # the create command looks like this:
          # `micromamba create -n test-env python=<the corresponding version>`
          environment-name: test-env
          cache-environment: true
          create-args: >-
            python=3.10
            kim-api=2.3.0

      - name: Install dependencies
        shell: bash -el {0}
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel twine

      - name: Build and publish
        shell: bash -el {0}
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME_OPENKIM }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD_OPENKIM }}
        run: |
          python setup.py sdist
          twine upload dist/*
