name: test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          # the create command looks like this:
          # `micromamba create -n test-env python=<the corresponding version>`
          environment-name: test-env
          cache-environment: true
          create-args: >-
            python=${{ matrix.python-version }}
            kim-api=2.3.0

      - name: Install KIM model
        shell: bash -el {0}
        run: |
          kim-api-collections-management install user SW_StillingerWeber_1985_Si__MO_405512056662_006

      - name: Install
        shell: bash -el {0}
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[test]

      - name: Test with pytest
        shell: bash -el {0}
        run: |
          cd tests
          pytest

